name: Trigger-Localisation-Builds

on:
  workflow_dispatch:
     inputs:
      Language:
         description: "Select All languages to build"
         required: true
         type: choice
         options:
          - ALL
      Preset:
         description: "Select individual language to build"
         required: true
         type: string
    

jobs:

  Trigger-Localisation-Builds:
     name:
     runs-on: ubuntu-22.04
     strategy:
      matrix:
        language: [PT-BR, DE, ES, FR, IT, JA, KO, PL, RU, ZH]
     steps:
      - name: Invoke workflow Brazilian in repo
        if: ${{ github.event.inputs.Language }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-${{ matrix.language }}
          token: ${{ secrets.GH_TOKEN }} 
        continue-on-error: false 
      - name: Invoke workflow Brazilian in repo
        if: ${{ github.event.inputs.Preset }} == ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build.yml
          repo: YoYoGames/GameMaker-Manual-${{ github.event.inputs.Preset }}
          token: ${{ secrets.GH_TOKEN }} 
        continue-on-error: false 


                                                                       